version: "2"
checks:
  argument-count:
    config:
      threshold: 10
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
plugins:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
          mass_threshold: 40
  sonar-python:
    enabled: true
    config:
      minimum_severity: critical
